language: python
sudo: false

node_js:
  - "7"

python:
  - "2.7"

install:
  - nvm install 7
  - pip install yotta
  - npm install
  - npm run pxt:init
  - npm run pxt:install

script:
  - npm run test

cache:
  directories:
    - node_modules